

class big_ERROR(Exception):
    pass